### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by guangfnian** [hufeiya/ShanXun#1]
首先非常感谢。
本人是openwrt纯小白，之前从未接触过，路由器也是今天刚到的，所以不知道下过来的拨号器和心跳包该如何使用。所以能否简要的说明一下如何使用？感激不尽。

**Comment by hufeiya** [comment]
这个只要普通路由就可以了.发心跳包还是用电脑发,反正电脑关上几天也不会掉.当然ssh到openwrt更好.
你在sx_pi.py上填上账号密码,再sudo python sx_pi.py就行了(Linux),可能Windows还要装python环境.
本只打算自己用,毕竟算法也不是自己的,有问题可以请教原作者realityone
还有要更改fuck.py的账号,如果不是浙工大的可能那个ip也要改,因为有的学校不一样,你要知道你学校接收心跳包的服务器的ip,用wireshark抓包可得

**Comment by hufeiya** [comment]
还有要要更改fuck.py的账号,如果不是浙工大的可能那个ip也要改,你要知道你学校接收心跳包的服务器的ip,用wireshark抓包可得
