### ISSUE TITLE
NO acc right

### ISSUE THREAD

**Issue by shenxs** [hufeiya/ShanXun#3]
工大的,配置都没什么问题,就是会显示NO acc right
是不是和路由器有关,请问你用的什么路由器

**Comment by hufeiya** [comment]
就是最破的那种水星路由器,先测试下官方Window客户端能不能登录,能登录就应该不会no acc right

**Comment by shenxs** [comment]
官方Windows客户端？是什么

**Comment by hufeiya** [comment]
就是Windows下大家用的闪讯啊

**Comment by shenxs** [comment]
闪讯官方客户端的当然没问题

**Comment by hufeiya** [comment]
那我就不知道咯反正我没问题ʅ（´◔౪◔）ʃ

**Comment by shenxs** [comment]
可能是路由器的问题,闪讯的账号密码根本无法传递到路由器上

**Comment by hufeiya** [comment]
实在不行先用官方闪讯登录再改下代码单发心跳包

**Comment by shenxs** [comment]
Linux没有官方闪讯(>﹏<)

**Comment by hufeiya** [comment]
我说先用windows登录再切换linux发心跳（逃

**Comment by shenxs** [comment]
Subject Line (for proofing, doesn't show in actual email)
<https://www.digitalocean.com>                         == Deploy a Server
For Free! ==

  Your friend a247820400 has been using DigitalOcean – a cloud hosting
service designed just for developers – and thought you might want to give
it a shot. You can deploy a server in 55 seconds from our control panel or
use our simple API. 

 Because you’ve been invited by a friend, we’d like to give you a $10
credit to try it out. Just use this link to create an account and you’ll
be credited automatically.

 Redeem Your Credit
<https://cloud.digitalocean.com/accept?code=b1f02c667063fe&amp;utm_campaign=Referral_Invite&amp;utm_medium=Referral_Program&amp;utm_source=Mandrill>

  Happy Coding,
 DigitalOcean 

            © DigitalOcean <http://do.co/email_twitter>
<http://do.co/email_gplus> <http://do.co/email_facebook>
